
#include <jni.h>
/* Header for class IS_UltraSonic_Ultra_real */

#ifndef _Included_IS_UltraSonic_Ultra_real
#define _Included_IS_UltraSonic_Ultra_real
#ifdef __cplusplus
extern "C" {
#endif
#undef IS_UltraSonic_Ultra_real_FOCUS_TRAVERSABLE_UNKNOWN
#define IS_UltraSonic_Ultra_real_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef IS_UltraSonic_Ultra_real_FOCUS_TRAVERSABLE_DEFAULT
#define IS_UltraSonic_Ultra_real_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef IS_UltraSonic_Ultra_real_FOCUS_TRAVERSABLE_SET
#define IS_UltraSonic_Ultra_real_FOCUS_TRAVERSABLE_SET 2L
#undef IS_UltraSonic_Ultra_real_TOP_ALIGNMENT
#define IS_UltraSonic_Ultra_real_TOP_ALIGNMENT 0.0f
#undef IS_UltraSonic_Ultra_real_CENTER_ALIGNMENT
#define IS_UltraSonic_Ultra_real_CENTER_ALIGNMENT 0.5f
#undef IS_UltraSonic_Ultra_real_BOTTOM_ALIGNMENT
#define IS_UltraSonic_Ultra_real_BOTTOM_ALIGNMENT 1.0f
#undef IS_UltraSonic_Ultra_real_LEFT_ALIGNMENT
#define IS_UltraSonic_Ultra_real_LEFT_ALIGNMENT 0.0f
#undef IS_UltraSonic_Ultra_real_RIGHT_ALIGNMENT
#define IS_UltraSonic_Ultra_real_RIGHT_ALIGNMENT 1.0f
#undef IS_UltraSonic_Ultra_real_serialVersionUID
#define IS_UltraSonic_Ultra_real_serialVersionUID -7644114512714619750i64
#undef IS_UltraSonic_Ultra_real_serialVersionUID
#define IS_UltraSonic_Ultra_real_serialVersionUID 4613797578919906343i64
#undef IS_UltraSonic_Ultra_real_INCLUDE_SELF
#define IS_UltraSonic_Ultra_real_INCLUDE_SELF 1L
#undef IS_UltraSonic_Ultra_real_SEARCH_HEAVYWEIGHTS
#define IS_UltraSonic_Ultra_real_SEARCH_HEAVYWEIGHTS 1L
#undef IS_UltraSonic_Ultra_real_NOT_OBSCURED
#define IS_UltraSonic_Ultra_real_NOT_OBSCURED 0L
#undef IS_UltraSonic_Ultra_real_PARTIALLY_OBSCURED
#define IS_UltraSonic_Ultra_real_PARTIALLY_OBSCURED 1L
#undef IS_UltraSonic_Ultra_real_COMPLETELY_OBSCURED
#define IS_UltraSonic_Ultra_real_COMPLETELY_OBSCURED 2L
#undef IS_UltraSonic_Ultra_real_WHEN_FOCUSED
#define IS_UltraSonic_Ultra_real_WHEN_FOCUSED 0L
#undef IS_UltraSonic_Ultra_real_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define IS_UltraSonic_Ultra_real_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef IS_UltraSonic_Ultra_real_WHEN_IN_FOCUSED_WINDOW
#define IS_UltraSonic_Ultra_real_WHEN_IN_FOCUSED_WINDOW 2L
#undef IS_UltraSonic_Ultra_real_UNDEFINED_CONDITION
#define IS_UltraSonic_Ultra_real_UNDEFINED_CONDITION -1L
#undef IS_UltraSonic_Ultra_real_IS_DOUBLE_BUFFERED
#define IS_UltraSonic_Ultra_real_IS_DOUBLE_BUFFERED 0L
#undef IS_UltraSonic_Ultra_real_ANCESTOR_USING_BUFFER
#define IS_UltraSonic_Ultra_real_ANCESTOR_USING_BUFFER 1L
#undef IS_UltraSonic_Ultra_real_IS_PAINTING_TILE
#define IS_UltraSonic_Ultra_real_IS_PAINTING_TILE 2L
#undef IS_UltraSonic_Ultra_real_IS_OPAQUE
#define IS_UltraSonic_Ultra_real_IS_OPAQUE 3L
#undef IS_UltraSonic_Ultra_real_KEY_EVENTS_ENABLED
#define IS_UltraSonic_Ultra_real_KEY_EVENTS_ENABLED 4L
#undef IS_UltraSonic_Ultra_real_FOCUS_INPUTMAP_CREATED
#define IS_UltraSonic_Ultra_real_FOCUS_INPUTMAP_CREATED 5L
#undef IS_UltraSonic_Ultra_real_ANCESTOR_INPUTMAP_CREATED
#define IS_UltraSonic_Ultra_real_ANCESTOR_INPUTMAP_CREATED 6L
#undef IS_UltraSonic_Ultra_real_WIF_INPUTMAP_CREATED
#define IS_UltraSonic_Ultra_real_WIF_INPUTMAP_CREATED 7L
#undef IS_UltraSonic_Ultra_real_ACTIONMAP_CREATED
#define IS_UltraSonic_Ultra_real_ACTIONMAP_CREATED 8L
#undef IS_UltraSonic_Ultra_real_CREATED_DOUBLE_BUFFER
#define IS_UltraSonic_Ultra_real_CREATED_DOUBLE_BUFFER 9L
#undef IS_UltraSonic_Ultra_real_IS_PRINTING
#define IS_UltraSonic_Ultra_real_IS_PRINTING 11L
#undef IS_UltraSonic_Ultra_real_IS_PRINTING_ALL
#define IS_UltraSonic_Ultra_real_IS_PRINTING_ALL 12L
#undef IS_UltraSonic_Ultra_real_IS_REPAINTING
#define IS_UltraSonic_Ultra_real_IS_REPAINTING 13L
#undef IS_UltraSonic_Ultra_real_WRITE_OBJ_COUNTER_FIRST
#define IS_UltraSonic_Ultra_real_WRITE_OBJ_COUNTER_FIRST 14L
#undef IS_UltraSonic_Ultra_real_RESERVED_1
#define IS_UltraSonic_Ultra_real_RESERVED_1 15L
#undef IS_UltraSonic_Ultra_real_RESERVED_2
#define IS_UltraSonic_Ultra_real_RESERVED_2 16L
#undef IS_UltraSonic_Ultra_real_RESERVED_3
#define IS_UltraSonic_Ultra_real_RESERVED_3 17L
#undef IS_UltraSonic_Ultra_real_RESERVED_4
#define IS_UltraSonic_Ultra_real_RESERVED_4 18L
#undef IS_UltraSonic_Ultra_real_RESERVED_5
#define IS_UltraSonic_Ultra_real_RESERVED_5 19L
#undef IS_UltraSonic_Ultra_real_RESERVED_6
#define IS_UltraSonic_Ultra_real_RESERVED_6 20L
#undef IS_UltraSonic_Ultra_real_WRITE_OBJ_COUNTER_LAST
#define IS_UltraSonic_Ultra_real_WRITE_OBJ_COUNTER_LAST 21L
#undef IS_UltraSonic_Ultra_real_REQUEST_FOCUS_DISABLED
#define IS_UltraSonic_Ultra_real_REQUEST_FOCUS_DISABLED 22L
#undef IS_UltraSonic_Ultra_real_INHERITS_POPUP_MENU
#define IS_UltraSonic_Ultra_real_INHERITS_POPUP_MENU 23L
#undef IS_UltraSonic_Ultra_real_OPAQUE_SET
#define IS_UltraSonic_Ultra_real_OPAQUE_SET 24L
#undef IS_UltraSonic_Ultra_real_AUTOSCROLLS_SET
#define IS_UltraSonic_Ultra_real_AUTOSCROLLS_SET 25L
#undef IS_UltraSonic_Ultra_real_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define IS_UltraSonic_Ultra_real_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef IS_UltraSonic_Ultra_real_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define IS_UltraSonic_Ultra_real_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
#undef IS_UltraSonic_Ultra_real_REVALIDATE_RUNNABLE_SCHEDULED
#define IS_UltraSonic_Ultra_real_REVALIDATE_RUNNABLE_SCHEDULED 28L
#ifdef __cplusplus
}
#endif
#endif
