
#include <jni.h>
/* Header for class IS_UltraSonic_Ultra_canvas */

#ifndef _Included_IS_UltraSonic_Ultra_canvas
#define _Included_IS_UltraSonic_Ultra_canvas
#ifdef __cplusplus
extern "C" {
#endif
#undef IS_UltraSonic_Ultra_canvas_FOCUS_TRAVERSABLE_UNKNOWN
#define IS_UltraSonic_Ultra_canvas_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef IS_UltraSonic_Ultra_canvas_FOCUS_TRAVERSABLE_DEFAULT
#define IS_UltraSonic_Ultra_canvas_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef IS_UltraSonic_Ultra_canvas_FOCUS_TRAVERSABLE_SET
#define IS_UltraSonic_Ultra_canvas_FOCUS_TRAVERSABLE_SET 2L
#undef IS_UltraSonic_Ultra_canvas_TOP_ALIGNMENT
#define IS_UltraSonic_Ultra_canvas_TOP_ALIGNMENT 0.0f
#undef IS_UltraSonic_Ultra_canvas_CENTER_ALIGNMENT
#define IS_UltraSonic_Ultra_canvas_CENTER_ALIGNMENT 0.5f
#undef IS_UltraSonic_Ultra_canvas_BOTTOM_ALIGNMENT
#define IS_UltraSonic_Ultra_canvas_BOTTOM_ALIGNMENT 1.0f
#undef IS_UltraSonic_Ultra_canvas_LEFT_ALIGNMENT
#define IS_UltraSonic_Ultra_canvas_LEFT_ALIGNMENT 0.0f
#undef IS_UltraSonic_Ultra_canvas_RIGHT_ALIGNMENT
#define IS_UltraSonic_Ultra_canvas_RIGHT_ALIGNMENT 1.0f
#undef IS_UltraSonic_Ultra_canvas_serialVersionUID
#define IS_UltraSonic_Ultra_canvas_serialVersionUID -7644114512714619750i64
#undef IS_UltraSonic_Ultra_canvas_serialVersionUID
#define IS_UltraSonic_Ultra_canvas_serialVersionUID -2284879212465893870i64
#ifdef __cplusplus
}
#endif
#endif
