/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IS_UltraSonic_Ultra_virtual_Emitter_loc */

#ifndef _Included_IS_UltraSonic_Ultra_virtual_Emitter_loc
#define _Included_IS_UltraSonic_Ultra_virtual_Emitter_loc
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
